export const USE_DIFFUSE_MAP = 'USE_DIFFUSE_MAP';
export const USE_NORMAL_MAP = 'USE_NORMAL_MAP';
export const USE_SPECULAR_MAP = 'USE_SPECULAR_MAP';
export const USE_DEFAULT_COLOR = 'USE_DEFAULT_COLOR';
